name: OfflineCards
options:
  bundleIdPrefix: com.offlinecards
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

settings:
  SWIFT_VERSION: "5.9"
  IPHONEOS_DEPLOYMENT_TARGET: "17.0"

targets:
  OfflineCards:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: OfflineCards/OfflineCards
        excludes:
          - "**/.DS_Store"
    resources:
      - OfflineCards/OfflineCards/Resources/Assets.xcassets
      - OfflineCards/OfflineCards/Resources/en.lproj
      - OfflineCards/OfflineCards/Resources/uk.lproj
      - OfflineCards/OfflineCards/Resources/pl.lproj
      - OfflineCards/OfflineCards/Resources/de.lproj
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.offlinecards.OfflineCards
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_NSCameraUsageDescription: "Camera is used to scan barcodes and take photos of your cards"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}

  OfflineCardsTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - OfflineCards/OfflineCardsTests
    dependencies:
      - target: OfflineCards
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.offlinecards.OfflineCardsTests
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}

  OfflineCardsUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - OfflineCards/OfflineCardsUITests
    dependencies:
      - target: OfflineCards
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.offlinecards.OfflineCardsUITests
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
        TEST_TARGET_NAME: OfflineCards

schemes:
  OfflineCards:
    build:
      targets:
        OfflineCards: all
        OfflineCardsTests: [test]
        OfflineCardsUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - OfflineCardsTests
        - OfflineCardsUITests
    archive:
      config: Release
